version: '3.8'

services:
  api:
    build: .
    container_name: ete-monitoring-station-api
    restart: always
    environment:
      - DATABASE_URL=postgres://root:ete#2810@localhost:5432/emm
    ports:
      - '3333:3333'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: emm-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ete#2810
      POSTGRES_DB: emm
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
